jseidl/magic-areas

custom_components/magic_areas/__init__.py
=> Respecting entities disabled option

custom_components/magic_areas/binary_sensor.py, custom_components/magic_areas/sensor.py, custom_components/magic_areas/switch.py
Downgraded warn to info, shouldn't spam the logs anymore. 
Closes #8
=> fixed log severities

custom_components/magic_areas/__init__.py, custom_components/magic_areas/binary_sensor.py, custom_components/magic_areas/const.py, custom_components/magic_areas/sensor.py, custom_components/magic_areas/switch.py
Scrapped the config related properties on `MagicArea` class. Now whenever config data is needed, uses area.config.get() directly.
=> Moved all constants to const.py

README.md, custom_components/magic_areas/binary_sensor.py, custom_components/magic_areas/const.py
This pull request introduces the sleep_timeout configuration to set a differend timeout while sleep mode is active (#29).
Fixes also the documentation issue (#27).
=> Introducing sleep_timeout configuration

custom_components/magic_areas/__init__.py
Adding `device_class` introspection to non-registry entities.
Fixes/Closes  #35
=> added device_class introspection for StandaloneEntity

custom_components/magic_areas/binary_sensor.py
=> fixing issue where disable_state was not being considered

custom_components/magic_areas/binary_sensor.py
Fix #50
....just to met the preferred branch naming....
=> Fix lights turing on in an unoccupied area by disable_entity

README.md
=> This repo is a HACS default, update README

custom_components/magic_areas/__init__.py
Adding support for entities without devices that now can be added to areas in home assistant.
=> added support for entities without devices on the area registry

custom_components/magic_areas/__init__.py, custom_components/magic_areas/base.py, custom_components/magic_areas/const.py, custom_components/magic_areas/light.py
Magic Areas will create `$ROOM Lights` light groups for all areas. Will add enable/disable support in another feature
=> Added light group support

custom_components/magic_areas/base.py, custom_components/magic_areas/sensor.py
=> Added better error checking and logging for sensor.py

custom_components/magic_areas/binary_sensor.py
Was broken due rework, fixes #82
=> Fixing media players and device trackers not working as presence anymore

custom_components/magic_areas/const.py
This adds the vibration and the connectivity device class for presence detection. A vibration sensor could be attached on a chair for presence detection...
closes #91
=> Add binary sensor vibration / connectivity device class for presence detection

custom_components/magic_areas/__init__.py
Fixes #103. Fix by @danielbrunt57.
=> 2021.3.0 fix

custom_components/magic_areas/base.py, custom_components/magic_areas/binary_sensor.py, custom_components/magic_areas/config_flow.py, custom_components/magic_areas/const.py, custom_components/magic_areas/cover.py, custom_components/magic_areas/light.py, custom_components/magic_areas/media_player.py, custom_components/magic_areas/sensor.py
One of the PRs is not totally backwards compatible and I completely forgot (despite author have warned me). Instead of releasing a minor version (2.1.0) with the other PRs, I'm leaning towards merging #101 into the party and releasing `3.0.0` instead.
PRs included:
* https://github.com/jseidl/hass-magic_areas/pull/118
* https://github.com/jseidl/hass-magic_areas/pull/98
* https://github.com/jseidl/hass-magic_areas/pull/99
* https://github.com/jseidl/hass-magic_areas/pull/92
Huge thanks to @sti0 @KTibow and @caphm, you folks rock!
__Note: I had to rename the branch, for more info see conversation on #123__
=> Merge of PRs, including some fixes to bugs that were introduced by them

custom_components/magic_areas/config_flow.py
Added group resolution to fix bug #172
=> Added group resolution

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature-request.md
Creating new issue templates for feature requests and bug reports
=> Update issue templates

custom_components/magic_areas/light.py, custom_components/magic_areas/media_player.py
Media Player and Light Groups had breaking changes, this fixes it.
=> Fix for groups breaking change on home assistant 2022.4

custom_components/magic_areas/cover.py
Fixing bug reported by @andyinno on Discord.
=> Hotfix: cover without device class name fix

custom_components/magic_areas/__init__.py, custom_components/magic_areas/base.py, custom_components/magic_areas/light.py
=> Fixing light group attributes

custom_components/magic_areas/base.py, custom_components/magic_areas/config_flow.py, custom_components/magic_areas/light.py
This might solve config_flow breaking when you delete an entity from HA. Untested.
=> checking if entity is on self.all_entities (valid)

custom_components/magic_areas/__init__.py, custom_components/magic_areas/base.py, custom_components/magic_areas/light.py, custom_components/magic_areas/util.py
Something 🤷  happened and I lost all that code, fixed.
=> fixing regression

custom_components/magic_areas/base.py, custom_components/magic_areas/cover.py, custom_components/magic_areas/light.py, custom_components/magic_areas/media_player.py
Making all `unique_id`s a slugified version of the `name`.
=> uniqueid standardization

.github/ISSUE_TEMPLATE/config.yml
For links for other stuff, using GitHub Issues only for bugs
=> Add issue config.yml

custom_components/magic_areas/cover.py, custom_components/magic_areas/sensor.py
One of our code beautifiers is removing the tuple, hopefully that fixes
=> Device uom pair regression fix

custom_components/magic_areas/base.py
Meta Areas wasn't checking excluded entities, implemented logic
=> Meta area exclude entities

custom_components/magic_areas/translations/de.json
Easier to use Magic Areas for german users
=> Add german localization

custom_components/magic_areas/binary_sensor.py
=> Fixing condition to skip binary sensors w/o device class

custom_components/magic_areas/climate.py, custom_components/magic_areas/util.py
Got taken out during refactor (regression)
=> Adding back feature enable check to climate groups

custom_components/magic_areas/climate.py, custom_components/magic_areas/const.py, custom_components/magic_areas/media_player.py, custom_components/magic_areas/switch.py
Just like for light groups, now the other two also get a switch to toggle control.
=> Climate and Media player groups control switches

custom_components/magic_areas/binary_sensor.py, custom_components/magic_areas/config_flow.py, custom_components/magic_areas/const.py, custom_components/magic_areas/translations/en.json, custom_components/magic_areas/translations/es.json
You asked for it, you have it!
=> Health sensor configurable device classes

hacs.json, requirements-test.txt, requirements.txt, tests/test_threshold.py
This PR is a minor chore bumping up versions and merging release 4.0.1 back into the main branch.
The threshold sensor test passes locally but not on GitHub so working to solve that as well
=> Fixing threshold sensor test to pass on GitHub and minor version bumps + consolidation of latest releases

custom_components/magic_areas/manifest.json, hacs.json
=> Release 4.1.0

custom_components/magic_areas/translations/fr-FR.json
=> feat(translation): add french translation file

custom_components/magic_areas/base/presence.py, custom_components/magic_areas/helpers/area.py
Floor meta-areas were missing the icon. Now it shows correctly.
=> Show correct icon for floor meta areas

custom_components/magic_areas/translations/de.json, custom_components/magic_areas/translations/en.json
SSIA, also contains small typo fix in EN
=> Revision of DE translation

custom_components/magic_areas/__init__.py, custom_components/magic_areas/config_flow.py, custom_components/magic_areas/const.py, custom_components/magic_areas/translations/en.json
=> Add config flow option for enabling/disabling auto-reload

custom_components/magic_areas/translations/de.json
=> german translation for new auto-reload option

custom_components/magic_areas/climate.py, tests/conftest.py, tests/mocks.py, tests/test_climate.py, tests/test_cover.py
Fixing climate groups and updating new climate group class from upstream
Closes #468
=> Fix broken climate groups

custom_components/magic_areas/base/magic.py, custom_components/magic_areas/config_flow.py, custom_components/magic_areas/const.py, custom_components/magic_areas/translations/en.json
No more having your aggregates pick up CPU Temperature and mess it all up!
=> Ignore diagnostic and config entities

README.md
=> Updating readme to add reference to wiki post with demo

custom_components/magic_areas/base/magic.py, custom_components/magic_areas/base/presence.py, custom_components/magic_areas/config_flow.py, custom_components/magic_areas/const.py, custom_components/magic_areas/translations/de.json, custom_components/magic_areas/translations/en.json, custom_components/magic_areas/translations/es.json, custom_components/magic_areas/translations/fr.json, custom_components/magic_areas/translations/nl-NL.json, custom_components/magic_areas/translations/pt-BR.json, custom_components/magic_areas/translations/ta.json, tests/common.py
Hardcoded the duration of 60s. Useless option that just clutters the UI.
Closes https://github.com/jseidl/hass-magic_areas/issues/328
=> Removal of update_interval as an option

.devcontainer.json, scripts/setup
These changes is what i needed to make pytest work within vscode (as in testing bar in vscode itself)
=> changes needed to make pytest work from dev container

custom_components/magic_areas/config_flow.py, custom_components/magic_areas/const.py, custom_components/magic_areas/translations/en.json
This PR is adding translation keys and EN_US translation for a bunch of stuff
Nice!
=> Translation update for entities' states and attributes + config flow selects

.devcontainer.json, scripts/setup, tests/test_light.py
after i got the unittests to work in this branch (https://github.com/VPelt/hass-magic_areas/tree/test-light-feature) i added the unittests for the light feature
=> Test light feature2

custom_components/magic_areas/base/magic.py, custom_components/magic_areas/binary_sensor/presence.py, custom_components/magic_areas/media_player/__init__.py, custom_components/magic_areas/switch/media_player_control.py
=> Fix area default icon not showing up

custom_components/magic_areas/binary_sensor/wasp_in_a_box.py, custom_components/magic_areas/config_flow.py, custom_components/magic_areas/const.py, custom_components/magic_areas/translations/en.json, tests/test_wasp_in_a_box.py
I thought I had the logic right, turns out I didn't.
=> Fix broken wasp in a box

custom_components/magic_areas/binary_sensor/wasp_in_a_box.py
Doesn't work with named arguments
=> Fixing call_later calls

custom_components/magic_areas/light.py
Closes https://github.com/jseidl/hass-magic_areas/issues/471
=> Fix color mode resolution to not use deprecated constants

custom_components/magic_areas/translations/de.json
DE translation for https://github.com/jseidl/hass-magic_areas/pull/550
=> DE translation for wasp timeout

README.md, custom_components/magic_areas/binary_sensor/presence.py, custom_components/magic_areas/media_player/area_aware_media_player.py, custom_components/magic_areas/util.py, tests/test_climate_control.py
To reduce log spamming on reloads
=> Downgraded log levels
