- README.md
Fix documentation for `sleep_lights`. Added documentation for `passive_start`.
Closes #27 
Closes #37
> Fix documentation for sleep_lights + add passive_start doc.

- custom_components/magic_areas/__init__.py
- custom_components/magic_areas/binary_sensor.py
With the move of constants to a new file on #1, a bunch of redundant code was stripped in favor of using the `config` object directly. That broke for cases where `config` entry was not defined (area defined only on registry). This update initializes `voluptuous` schema with default configuration for those areas.
Closes #33
> Added default config initialization for areas without config entry

- README.md
I added a `vibration` `binary_sensor` to detect room presence. At first it doesn't work...after some debugging I figured out that it's necessary to add the unique_id option to a yaml-defined binary_sensor. Only if this happens magic_areas loads it through the EntityRegistry. 
Additionally I changed the supported types for `binary_sensors` according to the code, every defined type is supported (e.g. `vibration`). Not every type would make sense to measure presence - but it's technically possible.
> add more detail to readme

- custom_components/magic_areas/binary_sensor.py
Failure in check if disable state has changed was causing the light control routine to retrigger even if it changed to the same state. This PR fixes this issue.
> Fix bug which disable state change would not check if state actually changed

- custom_components/magic_areas/__init__.py
- custom_components/magic_areas/binary_sensor.py
- custom_components/magic_areas/const.py
- custom_components/magic_areas/sensor.py
This feature remove the following config options:
* `control_lights`
* `control_climate`
* `control_media`
Introduces a new parameter called `features` which is a list of feature names the user wants to enable for a given area. All features now come disabled by default.
In addition, feature name `aggregates` was added to support turning on/off sensor aggregates.
Users intending to keep the original features shall configure their YAML like the following example:
```
magic_areas:
living_room:
features:
- control_lights
- control_media
- control_climate
- aggregates
```
I'm working on how to set defaults for all areas but haven't arrived in a good solution yet. To come in a future update.
Closes #2 #18
> Changed feature enabling/disabled to use new features parameter

- custom_components/magic_areas/__init__.py
- custom_components/magic_areas/base.py
- custom_components/magic_areas/binary_sensor.py
- custom_components/magic_areas/config_flow.py
- custom_components/magic_areas/manifest.json
- custom_components/magic_areas/sensor.py
- custom_components/magic_areas/translations/en.json
Integration loads by setting `magic_areas:` on the YAML. Shouldn't be added from the UI (only configured). 
Added abort step with descriptive error message and also magic areas will refuse to load if `magic_areas:` isn't defined on the YAML file.
Fixes #85
> Removal of manual integration adding step

- custom_components/magic_areas/const.py
- custom_components/magic_areas/cover.py
This adds support for grouping multiple covers in an area (similar to the light_groups feature).
Individual groups are created depending on the device_class of the covers (i.e. shades re put into one group, curtains into another).
Inheritance from CoverGroup is there to enable editing the resulting groups in the entity registry, because CoverGroup itself does not provide unique_ids.
> Add support for cover groups

- custom_components/magic_areas/__init__.py
- custom_components/magic_areas/config_flow.py
- custom_components/magic_areas/const.py
- custom_components/magic_areas/translations/en.json
This splits the configuration options flow up into multiple steps and should serve as a basis going forward, before incorporating more features (as discussed in my other PRs).
There's an initial step for setting general options on the area, followed by a "feature select" step. Depending on the selected features, and if the features provide additional configuration options, there are more steps to follow.
Because the validation schema in the background has changed, this breaks backwards compatibility. I might add migration logic for old config entries, but am not yet certain about that.
> Multiple steps in options flow

- custom_components/magic_areas/base.py
- custom_components/magic_areas/binary_sensor.py
Can be used in automations to quickly get a list of which areas have active sensors without having to manually specify all areas to check/loop through.
> Add active_areas attribute to aggregate binary sensors of meta areas

- custom_components/magic_areas/light.py
Patches the signature of the created LightGroup objects such that light groups can be successfully created under HA 2021.8.0 and above. (Fixes #131 .)
> Update LightGroup signature.

- custom_components/magic_areas/sensor.py
The function was logically flawed. I used a string made of `{device_class/unit_of_measurement}` for a dict key (used for lookup) and when faced with an unit of measurement that has `/`, ta-da! 
Changing to another character was another bug waiting to happen, so I rewrote it and now should work regardless of the values on those attributes.
This (probably) fixes https://github.com/jseidl/hass-magic_areas/issues/208. I can't test it tho because I don't have a sensor that fits this case.
> Aggregate sensor device_class/unit of measure map key bug

- custom_components/magic_areas/base.py
- custom_components/magic_areas/cover.py
- custom_components/magic_areas/light.py
- custom_components/magic_areas/media_player.py
According to unique_id documentation, integration name should be omitted as it's automatically handled.
> removed integration name from unique ids bc is bad practice

- custom_components/magic_areas/light.py
Removed behavior of all lights turning on if none configured for occupied state. Should be pretty easy for one to assign all lights to the occupied state if that is desired.
Removing this default behavior allows you to abuse other states (say, `accented` or `extended`) to only have lights come up after a while or when some other state is `on`.
> Light Group "All Lights" turn_on behavior removal

- custom_components/magic_areas/util.py
Python 3.10 (Home Assistant current as of 2022.7 release) moved Iterable from `collections` into `collections.abc`. Fixed the import on `util.py`.
> Fix Iterable import on util.py

- custom_components/magic_areas/base.py
- custom_components/magic_areas/config_flow.py
Fix for #236. Reworked selectors slightly. Original implementation of selectors in Magic Areas was not very well implemented by me and was ignoring defaults and optionals.
In fact, the `EntitySelectors` does not support blank values at all so I had to create a new class extending it and checking if the value is null on validation and just allowing it. Seems to be working fine now.
> fixing defaults and optionals on selectors for config flow

- custom_components/magic_areas/__init__.py
This just solves the immediate error in #265; it doesn't actually use the new aliases parameter for anything, but it does let Magic Areas run normally.
> Update __init__.py to fix #265

- custom_components/magic_areas/__init__.py
- custom_components/magic_areas/binary_sensor.py
- custom_components/magic_areas/const.py
This closes #266 by replacing the `DEVICE_CLASS_*` variables with the new `(Binary)SensorDeviceClass` enums.
> Replacing the deprecated DEVICE_CLASS_ variables

- custom_components/magic_areas/const.py
Closes #256. Replacing #272 as it got in conflict and needed one more line.
> Adding SUN_DOMAIN (sun.sun) to the config flow entity filter

- .github/release-drafter.yml
I don't like the `v` in front of the versions, lets just do straight version numbers
> Fixing version number on release drafter

- custom_components/magic_areas/base.py
This allows now helpers (threshold sensors for eg) to be used as presence sensors. Old bug finally gets squatted!
> Fixing dict copy that was overwriting entity_id

- custom_components/magic_areas/light.py
Prevented control release when turning lights of through the main light group (all lights). Removed check as it was added when turning off lights from dark->bright was handled on the parent group (now moved to each group)
> Removed parent group control check 

- custom_components/magic_areas/__init__.py
- custom_components/magic_areas/config_flow.py
- custom_components/magic_areas/translations/en.json
This PR removes the auto-creation of areas on startup and instead goes to full config-flow setup per area individually. This addresses the difficulty removing the integration and also allow users to try out on a single area before committing, apart from allowing you to have only some areas "magic".
> Config flow setup

- custom_components/magic_areas/light.py
Closes https://github.com/jseidl/hass-magic_areas/issues/258. Magic Areas will no longer turn lights off if you enter a bright room with lights already on. Will still turn lights off if the room was already occupied and becomes bright.
> Checking if area was just occupied when bright before turning off

- custom_components/magic_areas/base/entities.py
- custom_components/magic_areas/binary_sensor.py
- custom_components/magic_areas/const.py
For sensors that make sense to report ON only if all entities are ON (e.g. connectivity, plug), Magic Areas does that like we have for sensors mean/sum.
Closes #271
> Adding support for binary sensors to act in ALL mode 

- custom_components/magic_areas/base/entities.py
- custom_components/magic_areas/light.py
Was using regular LightGroup entity without adding device_info. Created a wrapper around LightGroup and MagicEntity so we have device attribution simplified for those.
> Fix Meta-area Light Groups not showing up on area device

- .github/workflows/release.yaml
- .github/workflows/validation.yaml
Also changing to ReleaseFlow had to change out from the develop branch listeners to main branch listeners on the definition file.
> Fixed CI pipeline now that ha-blueprint is deprecated

- custom_components/magic_areas/base/entities.py
- custom_components/magic_areas/binary_sensor.py
- custom_components/magic_areas/const.py
Sensors that are suffering from interference or other form of false-positives may hold an area active incorrectly but when you go check the `active_sensors` attribute, it's gone. Fear no longer with this new attribute called `last_active_sensors` that never gets cleared!
> Adding last_active_sensors to better help debug flipping sensors

- custom_components/magic_areas/__init__.py
- custom_components/magic_areas/config_flow.py
- custom_components/magic_areas/util.py
Fixed all places that use `AreaEntry`.
Closes #312
> Generalizing Meta area object creation so we can centralize fixes 

- custom_components/magic_areas/util.py
Related to https://github.com/jseidl/hass-magic_areas/issues/313
> Add async to load_entities method in add_entities_when_ready

- custom_components/magic_areas/util.py
Magic Areas create area objects for the meta areas so the MagicArea class accepts a single type. Whenever HA adds more parameters to the Area object, it breaks us. 
Fortunately @tbrasser is using the beta branch which helps us figure out when those changes happen. 
Added the `labels` and `floor_id` items with default values which should last for a while.
> Adding Area default values for parameters that will be required in future versions

- custom_components/magic_areas/__init__.py
- custom_components/magic_areas/base/magic.py
Update the system to async_get_dr now that the main pieces have been deprecated in home assistant.  Removes warning in the logs.
> Update magic.py to use the async_get directly

- custom_components/magic_areas/base/magic.py
- custom_components/magic_areas/binary_sensor.py
- custom_components/magic_areas/config_flow.py
- custom_components/magic_areas/const.py
- custom_components/magic_areas/translations/de.json
- custom_components/magic_areas/translations/en.json
- custom_components/magic_areas/util.py
Areas for a while have icons now, we can just pull from it. For meta areas, MA will provide initial ones that the end-use can customize through HA natively.
> Use area icon instead of configuration value

- custom_components/magic_areas/sensor.py
This fix uses the most popular unit of measurement for a given device class and leaves to the group converter to deal with unit conversions. This means if your sensors are in one unit but you have a few stragglers, those should get converted and properly aggregated.
Removed the bit that checked for the first entry on `list(DEVICE_CLASS_UNITS[device_class])[0]` because the new option is just better (again, this integration is heavily opinionated).
This bug was originally reported by @tbrasser on Discord. His PR #391 and his research behind it were paramount on coming to this. Thanks a lot ❤️ !
> Fix unit of measurement resolution

- custom_components/magic_areas/const.py
Setting voluptuous schemas `extra` option to ignore (remove) extra keys. Shall solve options breaking and having people recreate areas. Finally! (I hope)
> Make schemas tolerant to extra keys

- custom_components/magic_areas/__init__.py
- custom_components/magic_areas/const.py
This PR adds a listener to the entity registry and reloads (currently all entries) when the registry is updated (entity is added or edited) with an `area_id`
> Reload Magic Areas entry when entity registry is updated

- custom_components/magic_areas/__init__.py
- custom_components/magic_areas/sensor.py
Thought I could remove it but looks like the entity registry is not populated beforehand so 🤷 . Will try to look at this again in a later time so I can focus on the new features.
> Add back listener for waiting HA to load

- .pre-commit-config.yaml
- custom_components/magic_areas/__init__.py
- custom_components/magic_areas/const.py
A previous PR added a listener to the entity registry that reloads the (all) areas when a change is made to the area of an entity. This PR adds the same but for devices.
> Add device registry update listener to reload areas

- custom_components/magic_areas/media_player/__init__.py
- custom_components/magic_areas/switch/climate_control.py
- custom_components/magic_areas/switch/fan_control.py
The functions that listens to area change events on the switch entities were lacking a check wether the event area ID matches ours (the event is for our area).
This affected only the new features Fan groups and Climate control. Added where missing.
> Fix switch dispatch listeners

- custom_components/magic_areas/media_player/__init__.py
- custom_components/magic_areas/switch/__init__.py
- custom_components/magic_areas/switch/media_player_control.py
Self-explanatory. This simplifies the media group by being as close to native as possible with the switch listening to area changes and issuing service calls to turn it off.
> Migrate media player control logic from media player group into switch

- custom_components/magic_areas/binary_sensor/ble_tracker.py
- custom_components/magic_areas/binary_sensor/wasp_in_a_box.py
As reported on https://github.com/jseidl/hass-magic_areas/issues/556 WIAB sensor lacked the restore state functionality of every other entity. 
Oops, my bad!
> Add restore state to WIAB binary sensor
